# Generated by Django 2.2.1 on 2019-06-03 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyincome',
            old_name='monthly_prop_tax',
            new_name='annual_expense_growth',
        ),
    ]
